name: Node.js CI/CD

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env.test file
      run: |
        echo "NODE_ENV=test" > .env.test
        echo "PORT=5000" >> .env.test
        echo "MONGODB_URI=mongodb://localhost:27017/test-db" >> .env.test
        echo "AWS_ACCESS_KEY_ID=test-key-id" >> .env.test
        echo "AWS_SECRET_ACCESS_KEY=test-secret-key" >> .env.test
        echo "AWS_REGION=us-east-1" >> .env.test
        echo "S3_BUCKET_NAME=test-bucket" >> .env.test
    
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Generate test coverage
      run: npm run test:coverage
      
    - name: Upload coverage as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage/